spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/homestockapp
    username: homestockapp
    password: 12345
server:
  port: 8080